feat: Add TruffleHog to sec lints
lidofinance/linters pull request #12
Opened 2022-04-27 07:14 UTC by dgusakov

2022-04-27 11:20 UTC, vgorkavenko approved these changes

2022-04-27 11:21 UTC, skhomuti commented on .github/actions/lint-security/action.yml
> +      uses: lidofinance/linters/.github/actions/lint-security/trufflehog@trufflehog
replace branch before merge

2022-04-27 11:22 UTC, skhomuti approved these changes

2022-04-27 11:23 UTC, skhomuti commented
Update readme please

2022-04-27 11:29 UTC, merged

2023-06-10 05:51 UTC, Ninathebrave1 requested changes

2023-06-10 05:51 UTC, Ninathebrave1 commented on .github/CODEOWNERS
> +* @lidofinance/automation
Yes..approve!